server:
  port: 8087
---
spring:
  datasource:
    name: cts
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cts?useUnicode=true&characterEncoding=utf8&serverTimezone=CTT&useSSL=false
    username: root
    password: 111111wwq
---
mybatis:
  mapper-locations: classpath:mapping/*/*.xml
  type-aliases-package: com.amio.cts.*.domain
---
#控制台打印sql
logging:
  level:
    com:
      amio:
        cts:
          repository: debug